appVersion: apps/v1
kind: Deployment
metadata:
  name: microk8s
  labels:
    app.kubernetes.io/name: microk8s
    process: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microk8s
      process: web
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: microk8s
        process: web
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: microk8s
        image: api
        imagePullPolicy: Never
        name: microk8s
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2


