apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-rs
  labels:
    app: helloworldapp-rs
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - name: helloworldapp
        image: helloworld/app:latest
        imagePullPolicy: Never